AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PawPals.io

Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Type: String
    Default: dev
  CallbackURL:
    Type: String
    Default: http://localhost:4200/auth/login
  LogoutURL:
    Type: String
    Default: http://localhost:4200/auth/logout

Resources:
  petpalsUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: PawPals
  petpalsUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref petpalsUserPool
      GenerateSecret: false
      ClientName: PawPals-app

